services:
  - type: web
    name: study-bot
    runtime: docker
    plan: free
    dockerfilePath: ./учет и контроль/Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
